name: the republic of chocolate
favicon: null
layout_spectrum: 0.82936
typography_spectrum: 0.59538
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B8B8'
    - '#000000'
    - '#807878'
    - '#000000'
    - '#000000'
  brandStrength: 0.3125
  lightness: 0.27277955403099063
  saturation: 0.4343461983886652
  rhythmicContrast: 0.15254304794853013
purpose:
  - name: null
    item: null
    url: null
