name: the republic of chocolate
favicon: null
layout_spectrum: 0.97092
typography_spectrum: 0.59538
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B8B8'
    - '#000000'
    - '#807878'
    - '#000000'
    - '#000000'
  brandStrength: 0.4375
  lightness: 0.625
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
